## Homework 2 

### Elena Farahbakhsh Touli


The environment we use in this Lab are as follows: 

In [1]:
import numpy as np
from numpy import linalg as LA

### Q1
In this question for a given matrix in the format of sparse matrix, which a matrix is indicated by 3 arrays: val, col_idx, and row_ptr which is a poiter to the rows of the non-zero elements of a matrix, and a given vector x we want to calculate the product of the matrix and the vector. To do so, we use the folloing code:  

In [10]:
def multip(x, val, col_idx, row_ptr):
    n = len(x)
    nn = []
    for i in range(n):
        nn.append(0)
    b = np.array(nn)

    for i in range(n):
        b[i] = 0
        for j in range(row_ptr[i], row_ptr[i + 1]):
            b[i] = b[i] + (val[j] * x[col_idx[j]])
    return b


For the test we use the following code: 

In [12]:
x = np.array([0,1,0,1,0,1])
val = np.array([3,2,2,2,1,1,3,2,1,2,3])
col = np.array([0,1,3,1,2,2,2,3,4,4,5])
row = np.array([0,3,5,6,8,9,11])
s = multip(x, val, col, row)
print("From the method")
print(s)
matrix = np.array([[3,2,0,2,0,0],[0,2,1,0,0,0],[0,0,1,0,0,0],[0,0,3,2,0,0],[0,0,0,0,1,0],[0,0,0,0,2,3]])
x = np.array([0,1,0,1,0,1])
print("From the multiplication")
print(matrix.dot(x))

From the method
[4 2 0 2 0 3]
From the multiplication
[4 2 0 2 0 3]


### Q2
In this question, we need to find the QR factorization of a given matrix as input. The function is as follows: 

In [5]:
''' QR factorization '''
def QRF(A):
    def proj(u,v):
        return (v.dot(u)/u.dot(u))*u

    n = len(A)
    u = np.empty([n,n])
    u[:,0] = A[:,0]
    for i in range(1,n):
        j = 0
        sum = 0
        while j < i:
            sum = sum + proj(u[:,j],A[:,i])
            j = j+1
        u[:,i] = A[:,i] - sum
    e = np.empty([n,n])

    for i in range(n):
        e[:,i] = u[:,i]/(LA.norm(u[:,i]))


    m = len(A[0])
    R = np.array([n,m])

    R = inverse(e).dot(A)

    q, r = np.linalg.qr(A)
    return e, R

Here I used inverse the function that I wrote for the question 3, instead we can use the function in pyhton that we can run the following: 

In [16]:
''' QR factorization '''
def QRF(A):
    def proj(u,v):
        return (v.dot(u)/u.dot(u))*u

    n = len(A)
    u = np.zeros((n,n))
    u[:,0] = A[:,0]
    for i in range(1,n):
        j = 0
        sum = 0
        while j < i:
            sum = sum + proj(u[:,j],A[:,i])
            j = j+1
        u[:,i] = A[:,i] - sum
    e = np.zeros((n,n))

    for i in range(n):
        e[:,i] = u[:,i]/(LA.norm(u[:,i]))


    m = len(A[0])
    R = np.array([n,m])

    R = LA.inv(e).dot(A)

    return e, R

For the test we use the following program: 

In [17]:
A = np.array([[1,4],[1,2]])
I = np.identity(2)
Q, R = QRF(A)
matrix = Q.transpose().dot(Q)-I
l = LA.norm(matrix, 'fro')
print(l)


3.1560822113208575e-16


Here I used a matrix $A=[[1,4],[1,2]]$ and I found the $Q$ by using the function $QRF$ and then I found the multiplication of the mutix $Q$ and it's transpose. I subtracted the identity matrix from the result and found the frobinuous norm of that. The result should be $0$ which by error it is. 

### Q3
The question is to solve the equation $Ax=b$ directly. To solve this equation directly we use the following method: 
We find the inverse of $A$ and multiply it with $x$. For finding the inverse of $A$ we use the following precedure:
we add another matrix $B$ which at the begining is Identity matrix and then we use elimination method to change the matrix $A$ to an identity matrix and same changes to $B$. $B$ is the inverse of $A$.

The code is written as follows: 


In [33]:
def inverse(matrix):
    A = matrix
    n = len(matrix)
    B = np.identity(n)
    for i in range(n):

        max = abs(A[i, i])
        s = i
        j = n - 1
        while j >= i:
            if abs(A[j, i]) > max:
                s = j
            j = j - 1
        #            change(s,i)
        v = np.copy(A[s])
        v1 = np.copy(B[s])
        A[s] = np.copy(A[i])
        B[s] = np.copy(B[i])
        A[i] = np.copy(v)
        B[i] = np.copy(v1)

        8#            diameter = 1
        a = A[i, i]
        A[i] = np.divide(A[i], a)
        B[i] = np.divide(B[i], a)
        #            lower = 0
        for j in range(i + 1, n):
            ss = (-A[j, i])
            A[j] = A[i] * ss + A[j]
            B[j] = B[i] * ss + B[j]
        #            upper = 0
        for j in range(0, i):
            kk = (-A[j, i])
            A[j] = A[i] * kk + A[j]
            B[j] = np.copy(B[i]) * kk + np.copy(B[j])
    
    return B

The test is as follows: 

In [35]:
matrix = np.array([[1,2,4],[1,0,2],[4,4,0]])
C = np.array([[1,2,4],[1,0,2],[4,4,0]])
D = inverse(matrix)
print(D.dot(C))

[[ 1.00000000e+00  0.00000000e+00  2.22044605e-16]
 [-5.55111512e-17  1.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


Here, I used a matrix $matrix = [[1,2,4],[1,0,2],[4,4,0]]$ and found the inverse of that by the method that I wrote and then multiplied it with matrix the result as it shows is the identity matrix.

For the bonus it means from the last three questions I chose the last one. question no 6.
In this question we need to find the blocked matrix-matrix production. To do so, I considered 2 matrices $A$ and $B$ and three numbers $M$, $N$ and $P$ as input. We want to divide the matrix to blockes and then find the multiplication of them. The code is as follows: 

In [ ]:
def mat_mat_prod(A,B, M, N, P):
    A = np.array([[1,2,3,5],[3,4,2,6]])
    B = np.array([[1,2],[2,1],[0,1],[1,0]])
    M = 2
    N = 2; P =2;
    m = len(A)
    p = len(B)
    n = len(B[0])

    # M is the no of the rows of a
    bm = int(m/M)
    # N is the no of the column of b
    bn = int(n/N)
    # P is the no of the column of c
    bp = int(p/P)

    a = np.zeros([bm, bp, M, P])
    b = np.zeros([bp, bn, P, N])
    c = np.zeros([bm, bn, M, N])
    for i in range(bm):
        for k in range(bp):
            for j in range(M):
                for t in range(P):
                    a[i,k,j,t] = A[i*bm+j, k*bp+t]

    for i in range(bp):
        for k in range(bn):
            for j in range(P):
                for t in range(N):
                    b[i,k,j,t] = B[i*bp+j,k*bn+t]

    for i in range(bm):
        for k in range(bn):
            c[i,k] = np.zeros((M, N))

    for i in range(bm):
        for j in range(bn):
            for k in range(bp):
                c[i,j] = c[i,j] + a[i,k,:,:].dot(b[k,j,:,:])

    C = np.zeros([m, n])
    for i in range(bm):
        for k in range(bn):
            for j in range(M):
                for t in range(N):
                    C[i*bm+j,k*bp+t] = c[i,k,j,t]
    return C

First I found blocks by four for loops for both matrices. And, then found the multiplication of them. The test is as follows:
