# **Lab 1: Matrix Algorithms**
**Edvin von Platen**

# **Abstract**


In this lab we implement the following matrix and vector algorithms: scalar product, matrix-vector product, matrix-matrix product, and the Euclidian norm.

# **Set up environment**

In [0]:
# Load neccessary modules.
from google.colab import files

import time
import numpy as np

from matplotlib import pyplot as plt
from matplotlib import tri
from matplotlib import axes
from mpl_toolkits.mplot3d import Axes3D

# **Introduction**


Matrix algorithms are commonly used for numerical computation, in this lab we implement some of the most common algorithms. All definitions can be found in the course lecture notes.

We will use the index notation from the lecture notes where $A=(a_{ij})$ denotes a matrix and $x=(x_i)$ is a column vector. 

# **Methods**

In this section we give the mathematical formula for each algorithm and the corresponding implementation.

### **Scalar Product**

The scalar product $(\cdot,\cdot)$ for two vectors $x,y\in R^n$ is defined as,
$$
(x,y) = \sum_{i=1}^n x_iy_i
$$

In [0]:
def scalar_product(x,y):
  res = 0
  for i in range(x.size):
    res += x[i]*y[i]
  return res

### **Matrix-Vector Product**

The matrix-vector product for a matrix $A\in R^{m\times n}$ and vector $x\in R^n$ is defined as,
$$
Ax = b, \ b \in R^m \text{  where } b_i = \sum_{j=1}^n a_{ij}x_j
$$

In [0]:
def matrix_vector_product(A,x):
  m, n = A.shape
  b = np.zeros(m)
  for i in range(m):
    for j in range(n):
      b[i] += A[i,j]*x[j]
  return b

### **Matrix-Matrix Product**

The matrix-matrix product $AB = C$ for the two matrices $A \in R^{m\times p} \text{ and } B\in R^{p\times n}$ is a matrix $C\in R^{m\times n}$ defined as,
$$
c_{ij} = \sum_{k = 1}^p a_{ik}b_{kj}
$$

In [0]:
def matrix_matrix_product(A,B):
  m, p_a = A.shape
  p_b, n = B.shape
  p = p_a 
  C = np.zeros((m,n))
  for i in range(m):
    for j in range(n):
      for k in range(p):
        C[i,j] += A[i,k]*B[k,j]
  return C 

### **Euclidian Norm**

The Euclidian norm, or $l^2$ norm, is induced by the Euclidian inner product in the inner product space $R^n$. The Euclidian inner product is also known as the *scalar product* which we implemented above. This means that for a vector $x\in R^n$ the Euclidian norm $\Vert \cdot \Vert_2$ is defined as,
$$
\Vert x \Vert_2 = \sqrt{(x,x)},
$$
where $(\cdot,\cdot)$ is the Euclidian inner product.

In [0]:
def euclidian_norm(x):
  return np.sqrt(scalar_product(x,x))

# **Results**

In this section we test the implementations above. 

In [22]:
print("########## SCALAR PRODUCT TESTS #############")
zero_vec = np.array([0,0,0])
ones_vec = np.array([1,1,1])
x = np.array([-10, 0, 2])
y = np.array([-1,-1,-1])
print("(" + str(zero_vec) + "," + str(ones_vec) + ") = " + str(scalar_product(zero_vec, ones_vec)))
print("(" + str(ones_vec) + "," + str(zero_vec) + ") = " + str(scalar_product(ones_vec, zero_vec)))
print("(" + str(ones_vec) + "," + str(ones_vec) + ") = " + str(scalar_product(ones_vec, ones_vec)))
print("(" + str(ones_vec) + "," + str(y) + ") = " + str(scalar_product(ones_vec, y)))
print("(" + str(x) + "," + str(y) + ") = " + str(scalar_product(x,y)))
print("(" + str(y) + "," + str(x) + ") = " + str(scalar_product(y,x)))
print("(" + str(x) + "," + str(x) + ") = " + str(scalar_product(x,x)))


print("\n########## MATRIX VECTOR PRODUCT TESTS  #############")

I = np.array([[1,0,0],[0,1,0],[0,0,1]])
A = np.array([[-1,1,-2], [1,1,1], [-1,-2,-1]])
print(str(I) + "" + str(zero_vec) + "^T = " + str(matrix_vector_product(I,zero_vec))+"^T")
print(str(I) + "" + str(ones_vec) + "^T = " + str(matrix_vector_product(I,ones_vec))+"^T")
print(str(A) + "" + str(ones_vec) + "^T = " + str(matrix_vector_product(A,ones_vec))+"^T")
print(str(A) + "" + str(y) + "^T = " + str(matrix_vector_product(A,y)) + "^T")


print("\n########## MATRIX MATRIX PRODUCT TESTS  #############")

A = np.array([[1,-1],[-1,1]])
B = np.array([[0,1,1,1,1],[1,0,1,1,1]])
C = np.array([[1,2,3],[4,5,6],[-1,-1,-1]])
print(str(I) + " * \n" + str(I) + " = \n " + str(matrix_matrix_product(I,I)))
print("")
print(str(A) + " * \n" + str(B) + " = \n " + str(matrix_matrix_product(A,B)))
print("")
print(str(C) + " * \n" + str(I) + " = \n " + str(matrix_matrix_product(C,I)))
print("")
print(str(I) + " * \n" + str(C) + " = \n " + str(matrix_matrix_product(I,C)))
print("")
print(str(C) + " * \n" + str(C) + " = \n " + str(matrix_matrix_product(C,C)))
print("")


print("\n########## EUCLIDIAN NORM TESTS  #############")

x1 = np.array([1,0,0,0,0])
x2 = np.array([1/np.sqrt(2), 1/np.sqrt(2)])
x3 = np.array([-1/np.sqrt(2), -1/np.sqrt(2)])
x4 = np.array([0])
x5 = np.array([-1,0,-1,0,-1])
print("||" + str(x1) + "|| = " + str(euclidian_norm(x1)))
print("||" + str(x2) + "|| = " + str(euclidian_norm(x2)))
print("||" + str(x3) + "|| = " + str(euclidian_norm(x3)))
print("||" + str(x4) + "|| = " + str(euclidian_norm(x4)))
print("||" + str(x5) + "|| = " + str(euclidian_norm(x5)))

########## SCALAR PRODUCT TESTS #############
([0 0 0],[1 1 1]) = 0
([1 1 1],[0 0 0]) = 0
([1 1 1],[1 1 1]) = 3
([1 1 1],[-1 -1 -1]) = -3
([-10   0   2],[-1 -1 -1]) = 8
([-1 -1 -1],[-10   0   2]) = 8
([-10   0   2],[-10   0   2]) = 104

########## MATRIX VECTOR PRODUCT TESTS  #############
[[1 0 0]
 [0 1 0]
 [0 0 1]][0 0 0]^T = [0. 0. 0.]^T
[[1 0 0]
 [0 1 0]
 [0 0 1]][1 1 1]^T = [1. 1. 1.]^T
[[-1  1 -2]
 [ 1  1  1]
 [-1 -2 -1]][1 1 1]^T = [-2.  3. -4.]^T
[[-1  1 -2]
 [ 1  1  1]
 [-1 -2 -1]][-1 -1 -1]^T = [ 2. -3.  4.]^T

########## MATRIX MATRIX PRODUCT TESTS  #############
[[1 0 0]
 [0 1 0]
 [0 0 1]] * 
[[1 0 0]
 [0 1 0]
 [0 0 1]] = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[ 1 -1]
 [-1  1]] * 
[[0 1 1 1 1]
 [1 0 1 1 1]] = 
 [[-1.  1.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.]]

[[ 1  2  3]
 [ 4  5  6]
 [-1 -1 -1]] * 
[[1 0 0]
 [0 1 0]
 [0 0 1]] = 
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [-1. -1. -1.]]

[[1 0 0]
 [0 1 0]
 [0 0 1]] * 
[[ 1  2  3]
 [ 4  5  6]
 [-1 -1 -1]] = 
 [[ 1.  2.  3.]
 [ 4.  5.  

# **Discussion**

All implemented algorithms appear to be working as intended. This was not too suprising as the algorithms are quite simple. However, it is still important to test the implementation to catch any potential mistakes.
