<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Lab-1:-Matrix-algorithms" data-toc-modified-id="Lab-1:-Matrix-algorithms-1"><span class="toc-item-num">1&nbsp;&nbsp;</span><strong>Lab 1: Matrix algorithms</strong></a></span></li><li><span><a href="#Abstract" data-toc-modified-id="Abstract-2"><span class="toc-item-num">2&nbsp;&nbsp;</span><strong>Abstract</strong></a></span></li><li><span><a href="#Set-up-environment" data-toc-modified-id="Set-up-environment-3"><span class="toc-item-num">3&nbsp;&nbsp;</span><strong>Set up environment</strong></a></span></li><li><span><a href="#Introduction" data-toc-modified-id="Introduction-4"><span class="toc-item-num">4&nbsp;&nbsp;</span><strong>Introduction</strong></a></span><ul class="toc-item"><li><span><a href="#The-Scalar-product" data-toc-modified-id="The-Scalar-product-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>The Scalar product</a></span></li><li><span><a href="#The-matrix-vector-product" data-toc-modified-id="The-matrix-vector-product-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>The matrix-vector product</a></span></li><li><span><a href="#The-matrix-matrix-vector" data-toc-modified-id="The-matrix-matrix-vector-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>The matrix-matrix vector</a></span></li><li><span><a href="#The-euclidian-norm" data-toc-modified-id="The-euclidian-norm-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>The euclidian norm</a></span></li><li><span><a href="#The-euclidian-distance" data-toc-modified-id="The-euclidian-distance-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>The euclidian distance</a></span></li></ul></li><li><span><a href="#Methods" data-toc-modified-id="Methods-5"><span class="toc-item-num">5&nbsp;&nbsp;</span><strong>Methods</strong></a></span><ul class="toc-item"><li><span><a href="#The-Scalar-product" data-toc-modified-id="The-Scalar-product-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>The Scalar product</a></span></li><li><span><a href="#The-matrix-vector-product" data-toc-modified-id="The-matrix-vector-product-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>The matrix-vector product</a></span></li><li><span><a href="#The-matrix-matrix-vector" data-toc-modified-id="The-matrix-matrix-vector-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>The matrix-matrix vector</a></span></li><li><span><a href="#The-euclidian-norm" data-toc-modified-id="The-euclidian-norm-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>The euclidian norm</a></span></li><li><span><a href="#The-euclidian-distance" data-toc-modified-id="The-euclidian-distance-5.5"><span class="toc-item-num">5.5&nbsp;&nbsp;</span>The euclidian distance</a></span></li></ul></li><li><span><a href="#Results" data-toc-modified-id="Results-6"><span class="toc-item-num">6&nbsp;&nbsp;</span><strong>Results</strong></a></span><ul class="toc-item"><li><span><a href="#The-Scalar-product" data-toc-modified-id="The-Scalar-product-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>The Scalar product</a></span></li><li><span><a href="#The-matrix-vector-product" data-toc-modified-id="The-matrix-vector-product-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>The matrix-vector product</a></span></li><li><span><a href="#The-matrix-matrix-vector" data-toc-modified-id="The-matrix-matrix-vector-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>The matrix-matrix vector</a></span></li><li><span><a href="#The-euclidian-norm" data-toc-modified-id="The-euclidian-norm-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>The euclidian norm</a></span></li><li><span><a href="#The-euclidian-distance" data-toc-modified-id="The-euclidian-distance-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>The euclidian distance</a></span></li></ul></li><li><span><a href="#Discussion" data-toc-modified-id="Discussion-7"><span class="toc-item-num">7&nbsp;&nbsp;</span><strong>Discussion</strong></a></span></li></ul></div>

<a href="https://colab.research.google.com/github/johanhoffman/DD2363-VT20/blob/Volkaa/Lab-1/Volkaa-Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab 1: Matrix algorithms**
**Matthis Manthe**

# **Abstract**

In this report, different simple and fundamental operations in the domain of linear spaces, like matrices and vectors multiplications, are implemented and tested against the corresponding Numpy functions. This first lab serves as an introduction to the different technologies, such as Jupyter or Google Colab, that we will use in the course.

A short statement on who is the author of the file, and if the code is distributed under a certain license. 

In [0]:
"""This program uses a template for lab reports in the course"""
"""DD2363 Methods in Scientific Computing, """
"""KTH Royal Institute of Technology, Stockholm, Sweden."""

# Copyright (C) 2019 Johan Hoffman (jhoffman@kth.se)

# This file is part of the course DD2363 Methods in Scientific Computing
# KTH Royal Institute of Technology, Stockholm, Sweden
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This template is maintained by Johan Hoffman
# Please report problems to jhoffman@kth.se

'KTH Royal Institute of Technology, Stockholm, Sweden.'

# **Set up environment**

To have access to the neccessary modules you have to run this cell. If you need additional modules, this is where you add them. 

In [0]:
# Load neccessary modules.
from google.colab import files

import time
import numpy as np

from matplotlib import pyplot as plt
from matplotlib import tri
from matplotlib import axes
from mpl_toolkits.mplot3d import Axes3D

# **Introduction**

We implement in this notebook 5 of the most basic operations on real vectors and matrices, using their corresponding definition. All the following definitions are taken from the first part of the course : [DD2363 course content.](https://kth.instructure.com/courses/17068/files/2484974?module_item_id=189855)

## The Scalar product

Given two real vectors $x,y\in \mathbb{R}^n$, we define the scalar product as $<x,y>=\sum_{i=1}^nx_iy_i$




## The matrix-vector product

Given a real matrix $A\in \mathbb{R}^{m*n}$ and a real vector $x\in \mathbb{R}^n$, we define the product $Ax=y$, with $y\in \mathbb{R}^n$ and $\forall i\in \mathbb{N}, i\leq n, y_i=\sum_{j=1}^ma_{ij}x_i$

## The matrix-matrix vector

Given two real matrices $A\in \mathbb{R}^{n*l}$ and $B\in \mathbb{R}^{l*m}$, we define the product $AB=C$ with $C\in \mathbb{R}^{n*m}$ and $\forall i,j\in \mathbb{N}, i\leq n, j\leq m, c_{ij}=\sum_{k=1}^la_{ik}b_{kj}$, $A=(a_{ik}), B=(b_{kj}), C=(c_{ij})$

## The euclidian norm

Given a real vector $x\in \mathbb{R}^n$, we define the euclidian norm of x as $||x||_2=<x,x>^{\frac{1}{2}}$, using the previously defined scalar product.

## The euclidian distance

Given two real vectors $x,y\in \mathbb{R}^n$, we define the euclidian distance as $d(x,y)=||x-y||_2$, using the previously defined euclidian norm.

# **Methods**

For all of the 5 implementations of these functions, we directly use the mathematical definitions developed in the introduction.

## The Scalar product

The inputs x and y can be lists or numpy arrays of real numbers. The function returns np.nan if they don't have the same size.

In [0]:
def scalar_product(x,y):
    if(len(list(x))!=len(list(y))): return np.nan
    return np.sum([x[i]*y[i] for i in range(len(x))])

## The matrix-vector product

In the input, A must be a matrix (a 2 dimensional numpy array or list) of real numbers, and x a list or numpy array of real numbers. If the size of the second dimension of A does not match the size of the vector x, the function returns np.nan.

In [0]:
def matrix_vector_product(A,x):
    if (A.shape[1]!=len(x)): return np.nan
    return np.array([np.sum([A[i,j]*x[j] for j in range(len(x))]) for i in range(A.shape[0])])

## The matrix-matrix vector

In the input, A and B must be a matrix (a 2 dimensional numpy array or list) of real numbers. If the size of the second dimension of A does not match the size of the first dimension of B, the function returns np.nan.

In [0]:
def matrix_matrix_product(A,B):
    if (A.shape[1]!=B.shape[0]): return np.nan
    return np.array([[np.sum([A[i,k]*B[k,j] for k in range(A.shape[1])]) for j in range(B.shape[1])] for i in range(A.shape[0])])

## The euclidian norm

In the input, x can be a list or numpy array of real numbers.

In [0]:
def euclidian_norm(x):
    return np.sqrt(scalar_product(x,x))

## The euclidian distance

In the input, x and y can be a list or numpy array of real numbers. If the size x and y are different, the funtion returns np.nan.

In [0]:
def euclidian_distance(x,y):
    if(len(list(x))!=len(list(y))): return np.nan
    return euclidian_norm(x-y)

# **Results**

We test the different implemented functions through some simple test cases. For each of the function others than the euclidian norm (for which there are no special cases), 2 normal test cases and 1 where the sizes of the input are not valid are tested. The result of the following code tests the validity of the implementation.

## The Scalar product

In [0]:
def test_scalar_product():
    x = np.array([1,2,3,4])
    y = np.array([1,1,1,1])
    print("x =  ",x)
    print("y = ", y)
    print("Function result : ", scalar_product(x,y))
    print("Numpy function result : ", np.dot(x,y))
    print("----------------")
    x = np.array([2.3,2.3,-3.7,4.2])
    y = np.array([-1.4,1.567,10.67,16])
    print("x =  ",x)
    print("y = ", y)
    print("Function result : ", scalar_product(x,y))
    print("Numpy function result : ", np.dot(x,y))
    print("----------------")
    x = np.array([1,2])
    y = np.array([2,3,4])
    print("x =  ",x)
    print("y = ", y)
    print("Function result : ", scalar_product(x,y))
    print("----------------")
    
print("Scalar product tests : ")
test_scalar_product()

Scalar product tests : 
x =   [1 2 3 4]
y =  [1 1 1 1]
Function result :  10
Numpy function result :  10
----------------
x =   [ 2.3  2.3 -3.7  4.2]
y =  [-1.4    1.567 10.67  16.   ]
Function result :  28.1051
Numpy function result :  28.1051
----------------
x =   [1 2]
y =  [2 3 4]
Function result :  nan
----------------


## The matrix-vector product

In [0]:
def test_matrix_vector_product():
    A = np.array([[2,4,6], [3,6,9], [1,2,1]])
    x = np.array([1,2,3])
    print("A = ", A)
    print("x = ", x)
    print("Function result : ", matrix_vector_product(A,x))
    print("Numpy function result : ", np.matmul(A,x))
    print("----------------")
    A = np.array([[2.5,4.4,-6.67], [3.67,6.4,9.2], [-1.89,2.9,1.78]])
    x = np.array([-1.4,1.567,10.67])
    print("A = ", A)
    print("x = ", x)
    print("Function result : ", matrix_vector_product(A,x))
    print("Numpy function result : ", np.matmul(A,x))
    print("----------------")
    A = np.array([[2,4], [3,6]])
    x = np.array([1,2,3])
    print("A = ", A)
    print("x = ", x)
    print("Function result : ", matrix_vector_product(A,x))
    print("----------------")
    
print("Matrix-vector product tests : ")
test_matrix_vector_product()

Matrix-vector product tests : 
A =  [[2 4 6]
 [3 6 9]
 [1 2 1]]
x =  [1 2 3]
Function result :  [28 42  8]
Numpy function result :  [28 42  8]
----------------
A =  [[ 2.5   4.4  -6.67]
 [ 3.67  6.4   9.2 ]
 [-1.89  2.9   1.78]]
x =  [-1.4    1.567 10.67 ]
Function result :  [-67.7741 103.0548  26.1829]
Numpy function result :  [-67.7741 103.0548  26.1829]
----------------
A =  [[2 4]
 [3 6]]
x =  [1 2 3]
Function result :  nan
----------------


## The matrix-matrix vector

In [0]:
def test_matrix_matrix_product():
    A = np.array([[2,4,6], [3,6,9]])
    B = np.array([[1,2,3], [4,5,6], [7,8,9]])
    print("A = ", A)
    print("B = ", B)
    print("Function result : ", matrix_matrix_product(A,B))
    print("Numpy function result : ", np.matmul(A,B))
    print("----------------")
    A = np.array([[2.4,4.6,6.67], [3.8,-6.7,-9.8], [1.8,2.7,1.4]])
    B = np.array([[1.7,2.45,-3.67], [17,2.78,3.34], [1.78,-2.45,3.8]])
    print("A = ", A)
    print("B = ", B)
    print("Function result : ", matrix_matrix_product(A,B))
    print("Numpy function result : ", np.matmul(A,B))
    print("----------------")
    A = np.array([[2,4], [3,6]])
    B = np.array([[1,2,3],[2,3,4],[4,5,6]])
    print("A = ", A)
    print("B = ", B)
    print("Function result : ", matrix_matrix_product(A,B))
    print("----------------")
    
print("Matrix-matrix product tests : ")
test_matrix_matrix_product()

Matrix-matrix product tests : 
A =  [[2 4 6]
 [3 6 9]]
B =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Function result :  [[ 60  72  84]
 [ 90 108 126]]
Numpy function result :  [[ 60  72  84]
 [ 90 108 126]]
----------------
A =  [[ 2.4   4.6   6.67]
 [ 3.8  -6.7  -9.8 ]
 [ 1.8   2.7   1.4 ]]
B =  [[ 1.7   2.45 -3.67]
 [17.    2.78  3.34]
 [ 1.78 -2.45  3.8 ]]
Function result :  [[  94.1526    2.3265   31.902 ]
 [-124.884    14.694   -73.564 ]
 [  51.452     8.486     7.732 ]]
Numpy function result :  [[  94.1526    2.3265   31.902 ]
 [-124.884    14.694   -73.564 ]
 [  51.452     8.486     7.732 ]]
----------------
A =  [[2 4]
 [3 6]]
B =  [[1 2 3]
 [2 3 4]
 [4 5 6]]
Function result :  nan
----------------


## The euclidian norm

In [0]:
def test_euclidian_norm():
    x = np.array([0,0])
    print("x = ", x)
    print("Function result ; ", euclidian_norm(x))
    print("Numpy function result : ", np.linalg.norm(x))
    print("----------------")
    x = np.array([1,2,3,4])
    print("x = ", x)
    print("Function result ; ", euclidian_norm(x))
    print("Numpy function result : ", np.linalg.norm(x))
    print("----------------")
    x = np.array([2.3,2.3,-3.7,4.2])
    print("x = ", x)
    print("Function result ; ", euclidian_norm(x))
    print("Numpy function result : ", np.linalg.norm(x))
    print("----------------")
    
print("Euclidian norm tests : ")
test_euclidian_norm()

Euclidian norm tests : 
x =  [0 0]
Function result ;  0.0
Numpy function result :  0.0
----------------
x =  [1 2 3 4]
Function result ;  5.477225575051661
Numpy function result :  5.477225575051661
----------------
x =  [ 2.3  2.3 -3.7  4.2]
Function result ;  6.473793323855805
Numpy function result :  6.473793323855805
----------------


## The euclidian distance

In [0]:
def test_euclidian_distance():
    x = np.array([1,2,3,4])
    y = np.array([1,1,1,1])
    print("x = ", x)
    print("y = ", y)
    print("Function result : ", euclidian_distance(x,y))
    print("Numpy function result : ", np.linalg.norm(x-y))
    print("----------------")
    x = np.array([2.3,2.3,-3.7,4.2])
    y = np.array([-1.4,1.567,10.67,16])
    print("x = ", x)
    print("y = ", y)
    print("Function result : ", euclidian_distance(x,y))
    print("Numpy function result : ", np.linalg.norm(x-y))
    print("----------------")
    x = np.array([1,2])
    y = np.array([2,3,4])
    print("x = ", x)
    print("y = ", y)
    print("Function result : ", euclidian_distance(x,y))
    print("----------------")
    
print("Euclidian distance tests : ")
test_euclidian_distance()

Euclidian distance tests : 
x =  [1 2 3 4]
y =  [1 1 1 1]
Function result :  3.7416573867739413
Numpy function result :  3.7416573867739413
----------------
x =  [ 2.3  2.3 -3.7  4.2]
y =  [-1.4    1.567 10.67  16.   ]
Function result :  18.972722234829668
Numpy function result :  18.972722234829668
----------------
x =  [1 2]
y =  [2 3 4]
Function result :  nan
----------------


# **Discussion**

These implementations match the results of the numpy associated functions. We could have handled more special cases, but the current state is enough in the context of this first lab.